---
development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: user
  password: pass
  socket: "/var/run/mysqld/mysqld.sock"
  database: demo_project_development
  host: databasehost
test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: user
  password: pass
  socket: "/var/run/mysqld/mysqld.sock"
  database: demo_project_test
  host: databasehost
production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: user
  password: pass
  socket: "/var/run/mysqld/mysqld.sock"
  database: demo_project_production
  host: databasehost
